### ISSUE TITLE
大佬，运行mitmweb -p 6666 -s sheep.py出错是什么问题呀。

### ISSUE THREAD

**Issue by lifengbing** [longhuan1999/sheep#10]
当前配置文件不存在，将使用默认配置求解！
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\threading.py", line 932, in _bootstrap_inne
r
    self.run()
  File "c:\programdata\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1370, in _readerthread

    buffer.append(fh.read())
  File "c:\programdata\anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid
 start byte
Addon error: Traceback (most recent call last):
  File "sheep.py", line 71, in response
    self.make_map_data(is_topic)
  File "sheep.py", line 159, in make_map_data
    if "Python" not in subp.communicate()[0]:
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "c:\programdata\anaconda3\lib\subprocess.py", line 1420, in _communicate
    stdout = stdout[0]
IndexError: list index out of range

**Comment by longhuan1999** [comment]
Windows的话要把utf-8改成gbk，最近的commit修复了对Windows的两处兼容性问题

**Comment by lifengbing** [comment]
> Windows的话要把utf-8改成gbk，最近的commit修复了对Windows的两处兼容性问题

改了之后还是报错，windows不配吗。。。

**Comment by longhuan1999** [comment]
> > Windows的话要把utf-8改成gbk，最近的commit修复了对Windows的两处兼容性问题
> 
> 改了之后还是报错，windows不配吗。。。

  你改的是哪？直接用最新的Code试试
