### ISSUE TITLE
关于 sheep_manual.py运行的问题

### ISSUE THREAD

**Issue by anymine94** [longhuan1999/sheep#6]
您好，我用终端运行 python3 sheep_manual.py，会直接
 D:\sheep\sheep> python3 sheep_manual.py
 D:\sheep\sheep>
这样，如果在PyCharm 中运行提示
Traceback (most recent call last):
  File "D:\sheep\sheep\sheep_manual.py", line 2, in <module>
    from autoSolve import auto_solve
  File "D:\sheep\sheep\autoSolve.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

进程已结束,退出代码1
如果用D:\sheep\sheep> mitmweb -p 6666 -s sheep_manual.py运行，显示
==========================================
[4, 9, 4, 14, 2, 15, 14, 11, 3, 16, 5, 9, 15, 7, 6, 8, 6, 2, 8, 1, 16, 2, 4, 1, 7, 16, 2, 15, 10, 3, 4, 11, 2, 8, 6, 11, 6, 6, 3, 2, 2, 9, 9, 3, 6, 14, 2, 8, 2, 10, 4, 6, 10, 1, 9, 3, 9, 5, 1, 3, 5, 9, 9, 7, 6, 3, 14, 4, 9, 1, 14, 15, 16, 7, 11, 11, 7, 7, 5, 10, 9, 8, 10, 10, 2, 15, 3, 3, 1, 15, 4, 4, 5, 1, 1, 6, 3, 5, 15, 11, 4, 1, 8, 16, 2, 1, 10, 8, 9, 2, 14, 6, 14, 1, 16, 5, 15, 10, 1, 2, 4, 8, 4, 11, 7, 15, 11, 5, 4, 16, 8, 7, 5, 10, 5, 3, 11, 9, 15, 16, 5, 6, 16, 4, 11, 4, 10, 10, 7, 4, 2, 8, 1, 7, 5, 11, 14, 14, 3, 8, 15, 1, 15, 2, 5, 3, 7, 14, 16, 16, 3, 3, 5, 10, 11, 14, 16, 7, 5, 1, 6, 8, 14]
==========================================
已将当前关卡数据保存到当前路径下 map_data.json 文件！

将使用配置文件 config.json 的配置求解！
开始求解，请稍等60秒...
失败
失败
失败

普通模式进度：61/60自动求解超时！当前算法有些力不从心，建议放弃挑战并重新开始！
==========================================
Loading script sheep_manual.py
Traceback (most recent call last):

我应该怎么去运行sheep_manual.py，是不是autoSolve.py里面使用了mitmproxy的代码呢

**Comment by longhuan1999** [comment]
问题：ModuleNotFoundError: No module named 'requests' （Python没有安装requests模块）
解决：pip install requests

**Comment by anymine94** [comment]
依旧还是一样
PS D:\sheep\sheep> pip install requests   
Requirement already satisfied: requests in c:\users\zqy\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zqy\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\zqy\appdata\local\programs\python\python310\lib\site-packages (from requests) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\zqy\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zqy\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
PS D:\sheep\sheep> python3 sheep_manual.py
PS D:\sheep\sheep> 
这个是终端提示
C:\Users\xxx\PycharmProjects\pythonProject\venv\Scripts\python.exe D:/sheep/sheep/sheep_manual.py
Traceback (most recent call last):
  File "D:\sheep\sheep\sheep_manual.py", line 2, in <module>
    from autoSolve import auto_solve
  File "D:\sheep\sheep\autoSolve.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

进程已结束,退出代码1
这个是运行提示

**Comment by Angusvencent** [comment]
改成python sheep_manual.py试试，我之前也有这个问题，改成python之后用Anaconda自带的powershell运行完美解决。照代码看你还有可能是改过文件地址？重新部署一下试试

**Comment by anymine94** [comment]
> 改成python sheep_manual.py试试，我之前也有这个问题，改成python之后用Anaconda自带的powershell运行完美解决。照代码看你还有可能是改过文件地址？重新部署一下试试

谢谢了，还真的是这个问题，把所有代码改成python去掉后面的3都能使用了。。

**Comment by wurenzaiting** [comment]
==========================================
已将当前关卡数据保存到当前路径下 map_data.json 文件！

将使用配置文件 config.json 的配置求解！
开始求解，请稍等60秒...
失败
失败
失败
Exception in thread Thread-129:
Exception in thread Thread-131:
Exception in thread Thread-132:
Traceback (most recent call last):
Traceback (most recent call last):
  File "F:\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
Traceback (most recent call last):
  File "F:\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
  File "F:\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "F:\Anaconda3\lib\threading.py", line 910, in run
    self.run()
    self.run()
  File "F:\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Anaconda3\lib\threading.py", line 910, in run
  File "F:\Anaconda3\lib\subprocess.py", line 1479, in _readerthread
    self._target(*self._args, **self._kwargs)
  File "F:\Anaconda3\lib\subprocess.py", line 1479, in _readerthread
    self._target(*self._args, **self._kwargs)
    buffer.append(fh.read())
  File "F:\Anaconda3\lib\subprocess.py", line 1479, in _readerthread
  File "F:\Anaconda3\lib\codecs.py", line 322, in decode
    buffer.append(fh.read())
  File "F:\Anaconda3\lib\codecs.py", line 322, in decode
普通模式进度：1/60    buffer.append(fh.read())
    (result, consumed) = self._buffer_decode(data, self.errors, final)
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte
None
  File "F:\Anaconda3\lib\codecs.py", line 322, in decode
None
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte
None
普通模式进度：61/60自动求解超时！当前算法有些力不从心，建议放弃挑战并重新开始！

**Comment by wurenzaiting** [comment]
git pull https://github.com/BugMaker888/sheep也没有用 是不是哪里配置错误？
